spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: christy
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource